### ISSUE TITLE
Title of song overlaps with notes

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#87] opened 2019-06-10 23:19 UTC
Notes above ~C6 overlap with static text in view and are hardly readable, suggest to use 8va / 16va
![59217837-23f84b80-8bbf-11e9-87b8-d537edaf29d2](https://user-images.githubusercontent.com/2681872/59232994-50c45700-8bef-11e9-840a-dabab458dce7.png)

**Comment by NicolaasJKotze** [comment] 2020-04-20 18:48
Adding screenshots as reference to support retesting and regression testing in the future.

It would appear that resizing the window will not be a workaround.

In the attached screenshot there is a C#8, B7, and G9. Musescore highest seems to be G9. Not sure what instrument can play this, if a human can hear it, or if there are musical scores out there using it. Maybe Vitas can hit that high?

However, the low notes will also be a problem as can be seen in the screenshot.

**Version**: 0.7.3-PREVIEW1
**Operating System**: Kubuntu 19.10
**KDE Plasma Version**: 5.18.3
**KDE Frameworks Version**: 5.67.0
**Qt Version**: 5.12.4
**Kernel Version**: 5.3.0-46-generic
**OS Type**: 64-bit
**Processors**: 4 × Intel® Core™ i3 CPU M 350 @ 2.27GHz
**Memory**: 7,6 GiB of RAM

![image](https://user-images.githubusercontent.com/33121021/79787615-8f668a00-8347-11ea-8be1-edc8220903bd.png)

**Comment by pianobooster** [comment] 2020-04-22 17:16
This has low priority at the moment as Piano Booster is meant to be used by people playing along on a MIDI piano keyboard. Users would have to be very advanced to read piano music like this and would probably be reading the music from a printed sheet music instead. We could move the score down a bit if the window was enlarged . I have no plans to add Ottava 8va notation to piano booster which would be needed so the users could read what the note actually is. Thanks for contributing to the screen shots.

**Comment by pianobooster** [comment] 2020-05-30 17:58
I have moved display down a bit. Fixed in version 0.7.4-RC1 in the develop branch.

**Closed as completed by pianobooster** 2020-05-30 17:58 UTC
Labels: low priority
