### ISSUE TITLE
Wanted - Music that can be distributed with P. B. 

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#73] opened 2019-06-05 05:21 UTC
Hi all,

At the moment Piano Booster does not include any MIDI files with the program due to copyright reasons, Most modern pop/film music etc is copyrighted and so cannot be included without permission of the copyright holder. Midi music is a bit of a minefield because the arrangement/performance of the midi file  is also subject to copyright.

However any music which has the Creative Commons licence can be distribute with PB see this site for an example Mutopia Project. Basically I would like about 10 or 20 pieces for different levels of ability with the Creative Commons licence. Especially a few really simple pieces the total beginer.

Piano booster works best when there is an accompaniment as well as the piano part. (But don't worry about that yet - let find the suitable pieces first.)

Has anybody tried Band in a Box (windows + commercial) for automatically generating the accompaniment from just the Piano part?. I have just checked and this generated arrangement of the midi file is owned by the purchaser of the software. so if it any good we could run some pieces through Band in a Box and donate the resulting midi file as creative commons license. there is a 1 month free trial.

Anyway it would be great is you could suggest some pieces and perhaps we could put them all together and make some sort of tutorial.

Thanks

Louis 

Original post: http://piano-booster.2625608.n2.nabble.com/Wanted-Music-that-can-be-distributed-with-P-B-td2720056.html

**Comment by glixx** [comment] 2019-06-11 06:24
Good music: https://github.com/spiderbit/canta-media/tree/propose_0.2
Bruder Jakob
Fenster - Free Software Song
Frere Jacques (we have already)
Julia Ecklar - Eternal Flame
Perfect Fourth

**Comment by glixx** [comment] 2019-06-13 07:03
OhSusanna (http://piano-booster.2625608.n2.nabble.com/Creating-music-for-PianoBooster-using-MMA-Everyone-can-help-tp4167350p4251408.html)
http://piano-booster.2625608.n2.nabble.com/file/n4251408/OhSusanna.tar.gz is partially finished
Sorry no MMA at the moment, I could not find a proper groove.
And no MD file.

**Comment by pianobooster** [comment] 2020-04-23 19:03
This is a duplicate of a from post

**Closed as completed by pianobooster** 2020-04-23 19:03 UTC
Labels: enhancement, help wanted
