### ISSUE TITLE
Icon files aren't installed

### ISSUE THREAD

**Issue by yurivict** [pianobooster/PianoBooster#93] opened 2019-06-11 08:03 UTC
```icons``` are in the source tree but they aren't installed.
Please see how Arch linux installs them separately: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pianobooster-qt5-git

**Comment by glixx** [comment] 2019-06-11 10:01
Duplicate of https://github.com/captnfab/PianoBooster/issues/78

**Closed as completed by glixx** 2019-06-11 10:01 UTC
Labels: enhancement, help wanted
