### ISSUE TITLE
note names cannot be translated (spanish)

### ISSUE THREAD

**Issue by alejandro-anv** [pianobooster/PianoBooster#227] opened 2020-03-21 16:07 UTC
I've just trying pianobooster and some of the note names are not translated for spanish. Then, I oppened the file pianobooster_es.qm and checked if there where some missing translations but they are all ok, then, I think it may be hardcoded or something. 

Check this capture for example: https://imgur.com/a/e6gR048

(PianoBooster - Version 0.7.0)

**Comment by trebmuh** [comment] 2020-03-21 16:11
@alejandro-anv can you tell me which score is this so I can try to reproduce?

**Comment by alejandro-anv** [comment] 2020-03-24 09:57
D should be "Re"
E should be "Mi"
B should be "Si"

Others are ok and translation file has the correct data.

https://imgur.com/a/hYS2sfU

**Comment by trebmuh** [comment] 2020-03-24 13:58
@alejandro-anv thanks for that but that isn't what I asked for.
I'm asking you what **song** you're using:
![pianobooster-song](https://user-images.githubusercontent.com/8705846/77433618-de201300-6ddf-11ea-86c6-828c04529c00.png)

**Comment by louis-barman** [comment] 2020-04-08 13:00
@alejandro-anv Ok I think I have managed to reproduce the problem. Had you just changed the language selection from English to Spanish using the Setup/Preferences/Languages menu option? There is a very minor bug here in that the note names currently displayed on the screen do not change immediately but only when fresh notes are displayed. As this is a problem only when changing the language box which users would not be doing very often it is probably not worth fixing (but it might be an easy fix). @alejandro-anv  please can report back and confirm whether you had just changed the Languages section box? 

Also you should not be using version v0.7.0 at all as it does not work with MIDI piano keyboard due to this bug #207 . @alejandro-anv are you involved with a distribution build in which case you need to switch to version v0.7.2b as soon as you can. Thanks.

**Comment by pianobooster** [comment] 2020-05-14 14:34
Fixed int the develop branch.

**Closed as completed by pianobooster** 2020-05-14 14:34 UTC
Labels: low priority
